// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { poppins } from "../app/fonts/fonts";
import ClientProvider from "./ClientProvider"; // Importar el nuevo componente

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* Llamamos a ClientProvider para manejar el contenido */}
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
