// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { poppins } from "../app/fonts/fonts";
import ClientProvider from "./ClientProvider"; // Importar el nuevo componente

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* Llamamos a ClientProvider para manejar el contenido */}
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
